### ISSUE TITLE
Plugin not working for Scala 2.10.0-M7

### ISSUE THREAD

**Issue by agile-jordi** [skipoleschris/xsbt-cucumber-plugin#13]
Please, could you cross-compile so that I can use the plugin for Scala 2.10.0-M7?

When using sbt 0.12.1 it was complaining about:
module not found: templemore#sbt-cucumber-integration_2.10;0.7.0

I just downloaded your sources, added that version of Scala to crossScalaVersions and it worked. I'm afraid the current sbt-cucumber-integration uses the old naming convention for Scala versions (sbt-cucumber-integration_2.10_0-RC2) instead of the correct one since Scala 2.10.

Thank you very much!

**Comment by skipoleschris** [comment]
Hi,
I'm not sure it's quite that simple. What I'd found previously is that there are incompatibilities between different scala and cucumber-scala versions. For example, cucumber-scala was compiled with Scala 2.9.2 but only up to version 1.0.9. Then it was compiled against Scala 2.10.0-M7. Since 1.1.1 of cucumber-scala it has been compiled against Scala 2.10.0-RC1. I've had some fairly serious errors trying to run different versions of cucumber-scala with a version of Scala that they weren't compiled against. 

For this reason I took the decision to only publish releases of the plugin for the current stable Scala versions (2.9.1 and 2.9.2) plus the latest build of the next version (currently 2.10.0-RC2, but soon to be RC3 hopefully). I'd prefer not to support older development versions of 2.10.0 as this just causes a whole load of version and cross-testing pain.

As an aside, I'm hoping to work at getting cucumber-scala cross built against different Scala versions as this would then make life much easier as the plugin could just work against a single (latest) cucumber version.

Not sure what you mean by old naming convention for Scala versions. The cross build specification has to be a specific Scala version (e.g. 2.10.0-RC2) and this now generates artifacts where the version is just 2.10. Please let me know why you think this is wrong and I'll look into it further.

Any specific reason why you can't use 2.10.0-RC2 as the M7 release had quite a few bugs and there have been some significant changes since it was released? If you are really stuck and you can create a patch with an associated test project then I might be able produce a cross build as that would be much less work for me.

Regards,
Chris

**Comment by agile-jordi** [comment]
Hi,

Thank you for taking your time reviewing this.

Didn't know it wasn't that easy. Now I understand the issue. Your decision to only support the latest build of the next version sounds reasonable to me. I'll try to migrate my project to the latest 2.10 available version.

I just had assumed that the error I was getting (module not found: templemore#sbt-cucumber-integration_2.10;0.7.0) was due to that module being only deployed with a specific 2.10 Scala version (i.e. sbt-cucumber-integration_2.10-RC2) but I guess it was something else.

No specific reason to be using M7. I had some problem with another library but that other library was 2.10.0-M7 specific, no xsbt-cucumber-plugin's problem with that migration.

Regards,
Jordi

**Comment by agile-jordi** [comment]
By the way: I just did the test and everything worked flawlessly: http://func.io/post/36452127031/bdd-made-easy-in-scala-with-sbt-and-cucumber

Thank you very much again!

Jordi
