### ISSUE TITLE
xsbt ! sbt? 

### ISSUE THREAD

**Issue by ghost** [skipoleschris/xsbt-cucumber-plugin#18]
Should the ReadMe reference "xsbt-cucumber-plugin" and not "sbt-cucumber-plugin"?

"""
addSbtPlugin("templemore" % "sbt-cucumber-plugin" % "0.7.2")
"""

**Comment by skipoleschris** [comment]
Nope, it should be sbt-cucumber-plugin. I used to publish the artifacts as xsbt-cucumber-plugin but since it's so long since the sbt/xsbt split and the fact that most people now just refer to sbt to mean the new version I updated my published artifacts to match. 

At some point I might change the name of the github project but there are plently of links out there to it that it's not something I want to do at the moment.
