### ISSUE TITLE
Add Support for CLI options passed to Cucumber Main

### ISSUE THREAD

**Issue by randomcoder** [skipoleschris/xsbt-cucumber-plugin#20]
When running the cucumber task with `--dry-run` then the option gets processed as a _name_ parameter rather than as a _parameter/option_.

I think in general, as tags start with `@` and options start with `-` or `--` then the `isATag` & `isNotATag` is not quite sufficient a distinction and maybe a third option is needed to identify tags, options and names?

The use case this stops me doing is being able to quickly trial my test steps without actually trying to run them, which can cause other errors/failures when all I wish is to ensure that my step patterns are correct.

**Comment by skipoleschris** [comment]
This is now fixed with the features as follows:
- There is a new task `cucumber-dry-run` that runs cucumber with the --dry-run flag enabled
- There is a new boolean setting cucumberStrict to enable or disable strict mode
- There is a new boolean setting cucumberMonochrome to enable or disable monochrome mode

I think this fits better with the general approach of hiding the details of cucumber behind sbt settings. Hope that's oaky.
